services:
  webhook:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - repository:/app/repository
      - logs:/app/logs
    environment:
      - BRANCH=main
    restart: always

volumes:
  repository:
#    driver_opts:
#      type: nfs
#      o: addr=${NFS_ADDRESS},nfsvers=4
#      device: ${NFS_PATH}
  logs: