services:
  webhook:
    build: .
    ports:
      - "7000:7000"
    volumes:
      - repository:/app/repository
      - secrets:/app/secrets
      - logs:/app/logs
    environment:
      - BRANCH=main
      - REPO_PATH=/app/repository
      - GIT_URL_SSH=git@github.com:your/repo.git
    restart: always
volumes:
  repository:
#    driver_opts:
#      type: nfs
#      o: addr=${NFS_ADDRESS},nfsvers=4
#      device: ${NFS_PATH}
  logs:
  secrets: